package assemble

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
	"time"

	"github.com/holandyoung/unlock-catalog/internal/catalogv1"
	"github.com/holandyoung/unlock-catalog/internal/signing"
)

const signedFixtureReadme = `# Catalog V1 signed fixtures

These synthetic fixtures are generated by TestSignedFixturesMatchGenerated.
They contain public trust roots, signatures, and immutable release bytes only.
The deterministic signing material exists only in test code, is marked TEST
ONLY, and must never be used for production custody or authorization.

The data and exec cases use disjoint roots and exact permission sets. Each
positive case includes an R1 trust root, an R1-to-R2 threshold-signed bridge,
a manifest accepted by both roots, immutable objects, archive bytes, and a
deterministic tar.zst package. The negative cases isolate bad signature,
trust root, source identity, permission, artifact digest, artifact length,
artifact path, revocation, and offline package behavior.
`

type signedFixtureMetadata struct {
	ExpectedSourceID   string                 `json:"expectedSourceId"`
	GrantedPermissions []catalogv1.Permission `json:"grantedPermissions"`
	VerifyAt           time.Time              `json:"verifyAt"`
	ExpectedFailure    string                 `json:"expectedFailure,omitempty"`
	ArtifactID         string                 `json:"artifactId,omitempty"`
}

func TestSignedFixturesMatchGenerated(t *testing.T) {
	generatedRoot := t.TempDir()
	generated := filepath.Join(generatedRoot, "signed")
	generateSignedFixtures(t, generated)
	generateFixtureProvenance(t, generatedRoot)
	expectedRoot := filepath.Join("..", "..", "fixtures", "v1")
	expected := filepath.Join(expectedRoot, "signed")
	if os.Getenv("UPDATE_FIXTURES") == "1" {
		if err := os.RemoveAll(expected); err != nil {
			t.Fatal(err)
		}
		copyFixtureTree(t, generated, expected)
		writeFixtureFile(t, expectedRoot, "PROVENANCE.md", mustRead(t, filepath.Join(generatedRoot, "PROVENANCE.md")))
	}
	if got, want := fixtureTree(t, generated), fixtureTree(t, expected); !reflect.DeepEqual(got, want) {
		t.Fatalf("signed fixture drift\ngenerated: %v\nexpected: %v", sortedFixtureNames(got), sortedFixtureNames(want))
	}
	if got, want := mustRead(t, filepath.Join(generatedRoot, "PROVENANCE.md")), mustRead(t, filepath.Join(expectedRoot, "PROVENANCE.md")); !bytes.Equal(got, want) {
		t.Fatal("fixture provenance drift")
	}
}

func TestSignedFixturesSeparateDataAndExecAuthority(t *testing.T) {
	root := filepath.Join("..", "..", "fixtures", "v1", "signed", "positive")
	var dataRoot, execRoot TrustRoot
	readFixtureJSON(t, filepath.Join(root, "data", "current-root.json"), &dataRoot)
	readFixtureJSON(t, filepath.Join(root, "exec", "current-root.json"), &execRoot)
	for _, dataMaterial := range dataRoot.Keys {
		for _, execMaterial := range execRoot.Keys {
			if dataMaterial == execMaterial {
				t.Fatal("data and exec roots share public key material")
			}
		}
	}
	var dataMetadata, execMetadata signedFixtureMetadata
	readFixtureJSON(t, filepath.Join(root, "data", "metadata.json"), &dataMetadata)
	readFixtureJSON(t, filepath.Join(root, "exec", "metadata.json"), &execMetadata)
	if containsPermission(dataMetadata.GrantedPermissions, catalogv1.PermissionExecutable) {
		t.Fatal("data fixture grants executable permission")
	}
	if !containsPermission(execMetadata.GrantedPermissions, catalogv1.PermissionExecutable) {
		t.Fatal("exec fixture does not grant executable permission")
	}
}

func TestPublishedConformanceFixtureContract(t *testing.T) {
	root := filepath.Join("..", "..", "fixtures", "v1")
	required := []string{
		"PROVENANCE.md",
		"signed/negative/bad-signature/manifest.json",
		"signed/negative/bad-root/current-root.json",
		"signed/negative/bad-source-id/metadata.json",
		"signed/negative/bad-permission/metadata.json",
		"signed/negative/bad-digest/artifact.bin",
		"signed/negative/bad-length/artifact.bin",
		"signed/negative/bad-path/manifest.json",
		"signed/negative/bad-revocation/manifest.json",
		"signed/negative/bad-package/unlock-catalog-package-v1.tar.zst",
	}
	for _, relative := range required {
		info, err := os.Stat(filepath.Join(root, filepath.FromSlash(relative)))
		if err != nil {
			t.Fatalf("required conformance fixture %q: %v", relative, err)
		}
		if !info.Mode().IsRegular() || info.Mode().Perm() != 0o644 {
			t.Fatalf("required conformance fixture %q must be a mode 0644 regular file", relative)
		}
	}
}

func generateSignedFixtures(t *testing.T, output string) {
	t.Helper()
	writeFixtureFile(t, output, "README.md", []byte(signedFixtureReadme))
	dataManifest := generateSignedFixture(t, output, "data", "unlock-official-linux-amd64-static", []string{"data-a", "data-b", "data-c", "data-d"})
	generateSignedFixture(t, output, "exec", "unlock-official-linux-amd64-static-exec", []string{"exec-a", "exec-b", "exec-c", "exec-d"})

	var mutated SignedManifest
	if err := json.Unmarshal(dataManifest, &mutated); err != nil {
		t.Fatal(err)
	}
	mutated.Signed.Entries[0].DisplayName += " MUTATED"
	content, err := json.Marshal(mutated)
	if err != nil {
		t.Fatal(err)
	}
	writeFixtureFile(t, output, filepath.Join("negative", "data-manifest-payload-mutated.json"), content)
	generateConformanceNegativeFixtures(t, output, dataManifest)
}

func generateSignedFixture(t *testing.T, output, name, sourceID string, keyIDs []string) []byte {
	t.Helper()
	if len(keyIDs) != 4 {
		t.Fatal("fixture requires exactly four staged test key IDs")
	}
	candidate := filepath.Join("..", "..", "fixtures", "v1", "candidate", "valid", sourceID)
	payload := mustRead(t, filepath.Join(candidate, "manifest.payload.json"))
	request := mustRequest(t, candidate)
	manifest := mustManifest(t, payload)
	keys := testKeys(t, keyIDs...)
	current := testRoot(1, manifest.PublishedAt.Add(365*24*time.Hour), keys, keyIDs[0], keyIDs[1], keyIDs[2])
	next := testRoot(2, manifest.PublishedAt.Add(365*24*time.Hour), keys, keyIDs[0], keyIDs[1], keyIDs[3])
	rootDigest, rootPayload := rootSigningPayload(t, next)
	signedRoot, err := AssembleSignedRoot(current, next, []signing.Fragment{
		testFragment(rootPayload, rootDigest, keys[keyIDs[0]]),
		testFragment(rootPayload, rootDigest, keys[keyIDs[1]]),
	}, manifest.PublishedAt)
	if err != nil {
		t.Fatalf("assemble %s root: %v", name, err)
	}
	releaseRoot := filepath.Join(t.TempDir(), "release")
	release, err := Assemble(Options{
		CandidateDir: candidate, OutputDir: releaseRoot, ExpectedSourceID: sourceID,
		GrantedPermissions: request.Permissions, CurrentRoot: current, PublishedRoot: signedRoot,
		Now: manifest.PublishedAt,
	}, []signing.Fragment{
		testFragment(payload, requestDigest(t, candidate), keys[keyIDs[0]]),
		testFragment(payload, requestDigest(t, candidate), keys[keyIDs[1]]),
	})
	if err != nil {
		t.Fatalf("assemble %s release: %v", name, err)
	}
	caseRoot := filepath.Join(output, "positive", name)
	writeFixtureJSON(t, caseRoot, "current-root.json", current)
	writeFixtureJSON(t, caseRoot, "metadata.json", signedFixtureMetadata{
		ExpectedSourceID: sourceID, GrantedPermissions: request.Permissions,
		VerifyAt: manifest.PublishedAt.Add(time.Hour),
	})
	copyFixtureTree(t, release.Directory, filepath.Join(caseRoot, "release"))
	return mustRead(t, release.ManifestPath)
}

func writeFixtureJSON(t *testing.T, root, relative string, value any) {
	t.Helper()
	content, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	writeFixtureFile(t, root, relative, content)
}

func writeFixtureFile(t *testing.T, root, relative string, content []byte) {
	t.Helper()
	path := filepath.Join(root, relative)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatal(err)
	}
}

func copyFixtureTree(t *testing.T, source, destination string) {
	t.Helper()
	if err := filepath.Walk(source, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		if relative == "." {
			return os.MkdirAll(destination, 0o755)
		}
		target := filepath.Join(destination, relative)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("fixture source %q is not a regular file", relative)
		}
		input, err := os.Open(path)
		if err != nil {
			return err
		}
		defer input.Close()
		output, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
		if err != nil {
			return err
		}
		if _, err := io.Copy(output, input); err != nil {
			output.Close()
			return err
		}
		return output.Close()
	}); err != nil {
		t.Fatal(err)
	}
}

func fixtureTree(t *testing.T, root string) map[string][]byte {
	t.Helper()
	files := map[string][]byte{}
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if !info.Mode().IsRegular() || info.Mode().Perm() != 0o644 {
			return fmt.Errorf("fixture %q must be a mode 0644 regular file", path)
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		files[filepath.ToSlash(relative)] = mustRead(t, path)
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	return files
}

func sortedFixtureNames(files map[string][]byte) []string {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, fmt.Sprintf("%s:%d", name, len(files[name])))
	}
	sort.Strings(names)
	return names
}

func readFixtureJSON(t *testing.T, path string, target any) {
	t.Helper()
	decoder := json.NewDecoder(bytes.NewReader(mustRead(t, path)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		t.Fatal(err)
	}
}

func containsPermission(permissions []catalogv1.Permission, expected catalogv1.Permission) bool {
	for _, permission := range permissions {
		if permission == expected {
			return true
		}
	}
	return false
}
